# Generated by Django 4.0 on 2023-02-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='photo',
            field=models.ImageField(default='book.png', upload_to='books/'),
        ),
    ]
